# Project name is automatically derived from the filename (e.g., mozu.yaml -> project: mozu)
# No need to specify project field in this file

applications: []
# Example application structure:
# applications:
#   - name: example-service-prod
#     tier: x3.small
#     github:
#       owner: team-xquare
#       repo: example-service
#       branch: main
#       installationId: "12345678"
#       hash: latest
#     build:
#       gradle:
#         version: "17"
#         outputPath: "/build/libs/*.jar"
#         buildCmd: "./gradlew bootJar -x test --build-cache --no-daemon"
#       # or nodejs:
#       #   version: "18"
#       #   startCmd: "npm start"
#       #   buildCmd: "npm run build"
#       # or react:
#       #   version: "18"
#       #   outputPath: "/build"
#       #   buildCmd: "npm run build"
#       # or docker: {}  # Use existing Dockerfile from repository
#     endpoints:
#       - port: 8080
#         routes:
#           - example.dsmhs.kr

addons: []
# Example addon structures:
# addons:
#   # MySQL Database
#   - name: example-mysql
#     type: mysql
#     tier: x3.small
#     storage: 20Gi
#
#   # PostgreSQL Database
#   - name: example-postgres
#     type: postgresql
#     tier: x3.medium
#     storage: 50Gi
#
#   # Redis Cache
#   - name: example-redis
#     type: redis
#     tier: x3.micro
#     storage: 10Gi
#
#   # MongoDB
#   - name: example-mongodb
#     type: mongodb
#     tier: x3.medium
#     storage: 50Gi
#
#   # Apache Kafka
#   - name: example-kafka
#     type: kafka
#     tier: x3.large
#     storage: 100Gi
#
#   # RabbitMQ
#   - name: example-rabbitmq
#     type: rabbitmq
#     tier: x3.medium
#     storage: 20Gi
