{{- $namespace := (printf "%s-%s" .Values.project .Values.environment) }}
---
apiVersion: ecr.services.k8s.aws/v1alpha1
kind: Repository
metadata:
  name: {{ .Values.name }}-ecr-repo
  namespace: {{ $namespace }}
  annotations:
    services.k8s.aws/region: ap-northeast-2
spec:
  name: {{ $namespace }}/{{ .Values.name }}
  encryptionConfiguration:
    encryptionType: AES256
  imageScanningConfiguration:
    scanOnPush: true
  imageTagMutability: MUTABLE
  tags:
    - key: Environment
      value: {{ .Values.environment }}
    - key: ManagedBy
      value: ACK
    - key: Service
      value: {{ .Values.name }}