{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
{{- $githubFullname := printf "%s_%s" .Values.name .Values.environment | replace "-" "_" | lower }}
{{- $namespace := (printf "%s-%s" .Values.project .Values.environment) }}
{{- $githubAppID := 1172114 }}
{{- $githubInstallationID := .Values.githubInstallationID | int }}
{{- $argoEventsHost := "argo-events.xquare.app" }}
{{- $webhookPort := 12000 }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $fullname }}-github-webhook
  namespace: {{ $namespace }}
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  eventBusName: ci-eventbus
  github:
    {{ $githubFullname }}:
      repositories:
        - owner: {{ .Values.organization }}
          names:
            - {{ .Values.repository }}
      githubApp:
        privateKey:
          name: github-app-pem
          key: privateKey.pem
        appID: {{ $githubAppID }}
        installationID: {{ $githubInstallationID }}
      webhook:
        endpoint: /webhooks/{{ $fullname }}
        port: "{{ $webhookPort }}"
        method: POST
        url: "https://{{ $argoEventsHost }}"
      events:
        - push
      insecure: true
      active: true
      contentType: json
  service:
    ports:
      - name: {{ $fullname }}
        port: {{ $webhookPort }}
        targetPort: {{ $webhookPort }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    container:
      resources:
        requests:
          cpu: 2m
          memory: 20Mi
        limits:
          cpu: 50m
          memory: 50Mi
    tolerations:
      - key: xquare/ci-server
        operator: Equal
        value: 'true'
        effect: NoSchedule
