{{- range .Values.addons }}
{{- if eq .type "mongodb" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "addon.serviceName" . }}
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "addon.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  selector:
    {{- include "addon.selectorLabels" . | nindent 4 }}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "addon.name" . }}-data
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "addon.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .storage }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "addon.name" . }}
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "addon.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  serviceName: {{ include "addon.serviceName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "addon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "addon.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ include "addon.databaseName" . | quote }}
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "addon.name" . }}-data
{{- end }}
{{- end }}