{{- range .Values.applications }}
{{- if .github.hash }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.serviceName" . }}
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
  {{- range $endpoint := .endpoints }}
    - port: {{ $endpoint.port }}
      targetPort: {{ $endpoint.port }}
      name: "p{{ $endpoint.port }}"
  {{- end }}
{{- end }}
{{- end }}
