---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-service-account
  annotations:
    secrets.hashicorp.com/vso-kv-path: avp/data/ci-cd-pipeline
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: kaniko-sa.service-account-token
  namespace: {{ include "project.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: "kaniko-sa"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-workflow-role
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "patch", "list", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflows/finalizers", "workflowtaskresults", "workflowtasksets"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-workflow-rolebinding
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-workflow-role
subjects:
  - kind: ServiceAccount
    name: kaniko-sa