{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
{{- $namespace := (printf "%s-%s" .Values.project .Values.environment) }}

{{- if .Values.imageTag }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ $namespace }}
  name: {{ $fullname }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullname }}
{{- end }}
