{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
{{- $namespace := (printf "%s-%s" .Values.project .Values.environment) }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $fullname }}-secret
  namespace: {{ $namespace }}
spec:
  mount: xquare-kv
  path: {{ $fullname }}
  destination:
    name: {{ $fullname }}
    create: true
  hmacSecretData: true
  vaultAuthRef: {{ $namespace }}/{{ $namespace }}-vault-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ $fullname }}
  type: kv-v1
