{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ include "app.serviceName" . }}-github-webhook
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-webhook
  annotations: {}
spec:
  eventBusName: ci-eventbus
  service:
    ports:
      - port: {{ include "ci.webhookPort" $ }}
        targetPort: {{ include "ci.webhookPort" $ }}
  github:
    {{ include "ci.githubFullname" . }}:
      repositories:
        - owner: {{ .organization }}
          names:
            - {{ .repository }}
      githubApp:
        privateKey:
          name: github-app-pem
          key: privateKey.pem
        appID: {{ include "ci.githubAppID" $ }}
        installationID: {{ include "ci.githubInstallationID" . }}
      webhook:
        endpoint: /webhooks/{{ $.Values.project }}-{{ include "app.serviceName" . }}
        port: "{{ include "ci.webhookPort" $ }}"
        method: POST
        url: https://{{ include "ci.webhookHost" $ }}
      events:
        - push
        - ping
      insecure: false
      active: true
      contentType: json
{{- end }}