apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: ci-eventbus
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-eventbus
spec:
  nats:
    native:
      metadata:
        annotations:
      replicas: 3
      antiAffinity: false
      auth: none
      containerTemplate:
        resources:
          requests:
            cpu: 15m
            memory: 55Mi
          limits:
            cpu: 40m
            memory: 80Mi