---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-credentials
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-auth
  annotations:
    secrets.hashicorp.com/vso-kv-path: avp/data/ci-cd-pipeline
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ include "project.harborRegistry" . }}": {
          "username": "<harborUsername>",
          "password": "<harborPassword>",
          "auth": "<harborAuth>"
        }
      }
    }