{{- range $app := .Values.applications }}
{{- if $app.github.hash }}
{{- range $endpoint := $app.endpoints }}
{{- if $endpoint.routes }}
{{- range $route := $endpoint.routes }}
{{- $domain := regexFind "^[^/]+" $route }}
{{- $path := regexFind "/.*" $route | default "/" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $app.name }}-{{ $endpoint.port }}-{{ $domain | replace "." "-" }}{{ if ne $path "/" }}{{ $path | replace "/" "-" }}{{ end }}-httproute
  namespace: {{ include "project.namespace" $ }}
  labels:
    app.kubernetes.io/name: {{ $app.name | quote }}
    app.kubernetes.io/instance: {{ $app.name | quote }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "1.0.0"
    helm.sh/chart: project-1.0.0
    app.kubernetes.io/component: http-route
spec:
  parentRefs:
    - name: external-gateway
      namespace: gateway
      sectionName: http
    - name: external-gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - {{ $domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ $path }}
      {{- if ne $path "/" }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: ""
      {{- end }}
      backendRefs:
        - name: {{ $app.name }}
          port: {{ $endpoint.port }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}