{{- range .Values.applications }}
{{- if .imageTag }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.serviceName" . }}-imagepullsecrets
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-auth
  annotations:
    secrets.hashicorp.com/vso-kv-path: avp/data/ci-cd-pipeline
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ include "project.harborRegistry" $ }}": {
          "username": "<path:avp/data/ci-cd-pipeline#harborUsername>",
          "password": "<path:avp/data/ci-cd-pipeline#harborPassword>",
          "auth": "<path:avp/data/ci-cd-pipeline#harborAuth>"
        }
      }
    }
{{- end }}
{{- end }}