{{- range .Values.applications }}
{{- if .imageTag }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "app.serviceName" . }}
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v1
  mount: xquare-kv
  path: {{ include "app.vaultSecretName" (dict "project" $.Values.project "name" (include "app.serviceName" .)) }}
  destination:
    name: {{ include "app.vaultSecretName" (dict "project" $.Values.project "name" (include "app.serviceName" .)) }}
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "app.serviceName" . }}
  vaultAuthRef: {{ include "app.vaultAuthRef" (dict "projectNamespace" (include "project.namespace" $) "vaultAuth" (include "project.vaultAuth" $)) }}
{{- end }}
{{- end }}