{{- range .Values.applications }}
{{- if .imageTag }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "app.serviceName" . }}
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v1
  mount: xquare-kv
  path: {{ include "app.vaultSecretName" . }}
  destination:
    name: {{ include "app.vaultSecretName" . }}
    create: true
  vaultAuthRef: {{ include "app.vaultAuthRef" . }}
{{- end }}
{{- end }}