{{- if .Values.environments.stag }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
  namespace: {{ include "infrastructure.namespace" . }}-stag
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::786584124104:role/kaniko-ecr-push-role"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-workflow-role
  namespace: {{ include "infrastructure.namespace" . }}-stag
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "patch", "list", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflows/finalizers", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-workflow-rolebinding
  namespace: {{ include "infrastructure.namespace" . }}-stag
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-workflow-role
subjects:
  - kind: ServiceAccount
    name: kaniko-sa
{{- end }}

{{- if .Values.environments.prod }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
  namespace: {{ include "infrastructure.namespace" . }}-prod
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::786584124104:role/kaniko-ecr-push-role"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-workflow-role
  namespace: {{ include "infrastructure.namespace" . }}-prod
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "patch", "list", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflows/finalizers", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-workflow-rolebinding
  namespace: {{ include "infrastructure.namespace" . }}-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-workflow-role
subjects:
  - kind: ServiceAccount
    name: kaniko-sa
{{- end }}