{{- if .Values.environments.stag }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: ci-eventbus
  namespace: {{ include "infrastructure.namespace" . }}-stag
spec:
  nats:
    native:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      replicas: 3
      antiAffinity: false
      auth: none
      tolerations:
        - key: xquare/ci-server
          operator: Equal
          value: "true"
          effect: NoSchedule
      containerTemplate:
        resources:
          requests:
            cpu: 15m
            memory: 55Mi
          limits:
            cpu: 40m
            memory: 80Mi
{{- end }}

{{- if .Values.environments.prod }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: ci-eventbus
  namespace: {{ include "infrastructure.namespace" . }}-prod
spec:
  nats:
    native:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      replicas: 3
      antiAffinity: false
      auth: none
      tolerations:
        - key: xquare/ci-server
          operator: Equal
          value: "true"
          effect: NoSchedule
      containerTemplate:
        resources:
          requests:
            cpu: 15m
            memory: 55Mi
          limits:
            cpu: 40m
            memory: 80Mi
{{- end }}