{{- if .Values.environments.stag }}
{{- $githubPrivateKey := "<path:avp/data/github/ci-infrastructure#app_private_key>" }}
{{- $githubToken := "<path:avp/data/github/ci-infrastructure#token>" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-pem
  namespace: {{ include "infrastructure.namespace" . }}-stag
type: Opaque
data:
  privateKey.pem: "{{ $githubPrivateKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: {{ include "infrastructure.namespace" . }}-stag
type: Opaque
data:
  token: "{{ $githubToken | b64enc }}"
{{- end }}

{{- if .Values.environments.prod }}
{{- $githubPrivateKey := "<path:avp/data/github/ci-infrastructure#app_private_key>" }}
{{- $githubToken := "<path:avp/data/github/ci-infrastructure#token>" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-pem
  namespace: {{ include "infrastructure.namespace" . }}-prod
type: Opaque
data:
  privateKey.pem: "{{ $githubPrivateKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: {{ include "infrastructure.namespace" . }}-prod
type: Opaque
data:
  token: "{{ $githubToken | b64enc }}"
{{- end }}