{{- if .Values.environments.stag }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ .Values.project }}-stag
  namespace: {{ include "infrastructure.namespace" . }}-stag
spec:
  exporter:
    endpoint: "http://$(OTEL_NODE_IP):4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
{{- end }}

{{- if .Values.environments.prod }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ .Values.project }}-prod
  namespace: {{ include "infrastructure.namespace" . }}-prod
spec:
  exporter:
    endpoint: "http://$(OTEL_NODE_IP):4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
{{- end }}